
class CarsGlobals {
  static const List<String> carTypes = <String>['Family', 'Sports', 'Mini', 'Off-road'];
  static const List<String> companies = <String>[
    "Acura",
    "Alfa romeo",
    "Aro",
    "Asia",
    "Aston martin",
    "Audi",
    "Bentley",
    "Bmw",
    "Brilliance",
    "Bugatti",
    "Buick",
    "Byd",
    "Cadillac",
    "Chery",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Dacia",
    "Daewoo",
    "Daf",
    "Daihatsu",
    "Daimler",
    "Derways",
    "Dodge",
    "Eagle",
    "Faw",
    "Ferrari",
    "Fiat",
    "Ford",
    "Freightliner",
    "Gaz",
    "Geely",
    "Gmc",
    "Great wall",
    "Harley davidson",
    "Hino",
    "Honda",
    "Hummer",
    "Hyundai",
    "Ifa",
    "Ig",
    "Infiniti",
    "International",
    "Isuzu",
    "Iveco",
    "Jaguar",
    "Jeep",
    "Kamaz",
    "Kavz",
    "Kawasaki",
    "Kia",
    "Kraz",
    "Lamborghini",
    "Lancia",
    "Land rover",
    "Laz",
    "Lexus",
    "Liaz",
    "Lifan",
    "Lincoln",
    "Luaz",
    "Man",
    "Marz",
    "Maserati",
    "Maybach",
    "Maz",
    "Mazda",
    "Mercedes benz",
    "Mercury",
    "Mg",
    "Mini",
    "Mitsubishi",
    "Mitsuoka",
    "Moscvich",
    "Neoplan",
    "Nissan",
    "Nyssa",
    "Oldsmobile",
    "Opel",
    "Peugeot",
    "Plymouth",
    "Pontiac",
    "Porsche",
    "Proton",
    "Reliant",
    "Renault",
    "Renault samsung",
    "Rolls-royce",
    "Rover",
    "Saab",
    "Saturn",
    "Scion",
    "Seat",
    "Skoda",
    "Smart",
    "Ssang yong",
    "Subaru",
    "Talbot",
    "Tanye",
    "Tatra",
    "Tianye",
    "Toyota",
    "Uaz",
    "Ural",
    "Vauxhall",
    "Vaz",
    "Volkswagen",
    "Volvo",
    "Xin kai",
    "Zaz",
    "Zil",
  ];
}